services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=petclinic
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
    volumes:
      - mysql_data:/var/lib/mysql
 
  petclinic:
    image: mtbsoft/petclinic:war-mysql
    container_name: petclinic
    ports:
      - 8080:8080
    depends_on:
      - mysql
volumes:
  mysql_data:
